name: Company Service CI

on:
  push:
  pull_request:

jobs:
  test-company:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Give permission to mvnw
        run: chmod +x company/mvnw

      - name: Start Spring Boot app
        run: |
          cd company
          ./mvnw spring-boot:run > app.log 2>&1 &
          
          echo "Waiting for app to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8082/companies/count-all > /dev/null; then
              echo "App is ready!"
              break
            fi
            sleep 2
          done

      - name: Run company tests
        run: |
          cd company
          ./mvnw clean test

      - name: Print app logs on failure
        if: failure()
        run: cat company/app.log
